import apiClient from './apiClient';
import { IUser, ApiResponse } from '@/types';

export const userService = {
  // Get all users with optional filtering
  getAllUsers: async (params?: {
    role?: string | string[];
    isActive?: boolean;
    cohortId?: string;
    trackId?: string;
  }): Promise<ApiResponse<IUser[]>> => {
    const response = await apiClient.get('/users/all', { params });
    return response.data;
  },

  // Get users with pagination
  getUsers: async (params?: {
    role?: string | string[];
    isActive?: boolean;
    cohortId?: string;
    trackId?: string;
    page?: number;
    limit?: number;
  }): Promise<ApiResponse<{ users: IUser[]; pagination: any }>> => {
    const response = await apiClient.get('/users', { params });
    return response.data;
  },

  // Get all mentors
  getMentors: async (): Promise<ApiResponse<IUser[]>> => {
    const response = await apiClient.get('/users/mentors');
    return response.data;
  },

  // Get mentors for specific cohort and track
  getMentorsForTrack: async (
    cohortId: string,
    trackId: string
  ): Promise<ApiResponse<IUser[]>> => {
    const response = await apiClient.get(
      `/users/mentors/cohort/${cohortId}/track/${trackId}`
    );
    return response.data;
  },

  // Get all students
  getStudents: async (params?: {
    cohortId?: string;
    trackId?: string;
  }): Promise<ApiResponse<IUser[]>> => {
    const response = await apiClient.get('/users/students', {
      params,
    });
    return response.data;
  },

  // Get user by ID
  getUserById: async (id: string): Promise<ApiResponse<IUser>> => {
    const response = await apiClient.get(`/users/${id}`);
    return response.data;
  },

  // Get current user profile
  getCurrentUser: async (): Promise<ApiResponse<IUser>> => {
    const response = await apiClient.get('/auth/profile');
    return response.data;
  },

  // Create new user (admin only) - password is auto-generated by backend
  createUser: async (
    userData: Partial<IUser>
  ): Promise<ApiResponse<IUser>> => {
    const response = await apiClient.post('/users', userData);
    return response.data;
  },

  // Update user
  updateUser: async (
    id: string,
    userData: Partial<IUser>
  ): Promise<ApiResponse<IUser>> => {
    const response = await apiClient.put(`/users/${id}`, userData);
    return response.data;
  },

  // Update current user profile (should go through auth)
  updateProfile: async (
    userData: Partial<IUser>
  ): Promise<ApiResponse<IUser>> => {
    const response = await apiClient.patch('/auth/profile', userData);
    return response.data;
  },

  // Toggle user status
  toggleUserStatus: async (id: string): Promise<ApiResponse<IUser>> => {
    const response = await apiClient.patch(`/users/${id}/toggle-status`);
    return response.data;
  },

  // Assign tracks to mentor
  assignTracksToMentor: async (
    mentorId: string,
    trackIds: string[]
  ): Promise<ApiResponse<IUser>> => {
    const response = await apiClient.patch(`/users/${mentorId}/assign-tracks`, {
      trackIds,
    });
    return response.data;
  },

  // Remove tracks from mentor (no specific backend route found, using assign with empty array)
  removeTracksFromMentor: async (
    mentorId: string,
    trackIds: string[]
  ): Promise<ApiResponse<IUser>> => {
    const response = await apiClient.patch(`/users/${mentorId}/assign-tracks`, {
      trackIds: [], // Remove all or use proper backend method if exists
    });
    return response.data;
  },

  // Change password (should go through auth)
  changePassword: async (
    currentPassword: string,
    newPassword: string
  ): Promise<ApiResponse<void>> => {
    const response = await apiClient.post('/auth/change-password', {
      currentPassword,
      newPassword,
    });
    return response.data;
  },

  // Reset password (admin only)
  resetUserPassword: async (userId: string): Promise<ApiResponse<{generatedPassword: string}>> => {
    const response = await apiClient.post(`/users/${userId}/reset-password`);
    return response.data;
  },

  // Delete user
  deleteUser: async (id: string): Promise<ApiResponse<void>> => {
    const response = await apiClient.delete(`/users/${id}`);
    return response.data;
  },

  // Get user stats
  getUserStats: async (): Promise<ApiResponse<any>> => {
    const response = await apiClient.get('/users/stats');
    return response.data;
  },
};
