// Track-specific tool suggestions
export const trackTools = {
  'frontend-development': [
    'HTML5',
    'CSS3',
    'JavaScript',
    'TypeScript',
    'React',
    'Vue.js',
    'Angular',
    'Next.js',
    'Nuxt.js',
    'Tailwind CSS',
    'Bootstrap',
    'SASS/SCSS',
    'Webpack',
    'Vite',
    'Redux',
    'Zustand',
    'jQuery',
    'Figma',
    'Adobe XD',
  ],
  'backend-development': [
    'Node.js',
    'Express.js',
    'Python',
    'Django',
    'Flask',
    'FastAPI',
    'Java',
    'Spring Boot',
    'C#',
    '.NET',
    'PHP',
    'Laravel',
    'Ruby',
    'Ruby on Rails',
    'Go',
    'Rust',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'Docker',
    'AWS',
    'Azure',
  ],
  'fullstack-development': [
    'JavaScript',
    'TypeScript',
    'React',
    'Node.js',
    'Express.js',
    'Next.js',
    'Python',
    'Django',
    'PostgreSQL',
    'MongoDB',
    'Docker',
    'Git',
    'AWS',
    'REST APIs',
    'GraphQL',
    'Redux',
    'Tailwind CSS',
    'Jest',
    'Cypress',
  ],
  'mobile-development': [
    'React Native',
    'Flutter',
    'Dart',
    'Swift',
    'Kotlin',
    'Java',
    'Objective-C',
    'Xamarin',
    'Ionic',
    'Cordova',
    'Firebase',
    'SQLite',
    'Realm',
    'Xcode',
    'Android Studio',
    'Expo',
    'Redux',
    'MobX',
    'TestFlight',
    'Google Play Console',
  ],
  'product-management': [
    'Jira',
    'Confluence',
    'Trello',
    'Asana',
    'Notion',
    'Monday.com',
    'Slack',
    'Microsoft Teams',
    'Figma',
    'Miro',
    'Google Analytics',
    'Mixpanel',
    'Amplitude',
    'UserVoice',
    'Hotjar',
    'A/B Testing',
    'SQL',
    'Excel',
    'PowerBI',
    'Tableau',
  ],
  'product-design': [
    'Figma',
    'Adobe XD',
    'Sketch',
    'InVision',
    'Principle',
    'Framer',
    'Adobe Creative Suite',
    'Photoshop',
    'Illustrator',
    'After Effects',
    'Zeplin',
    'Marvel',
    'Balsamiq',
    'Axure RP',
    'Miro',
    'FigJam',
    'Protopie',
    'User Research',
    'Usability Testing',
    'Wireframing',
  ],
  'data-science': [
    'Python',
    'R',
    'SQL',
    'Pandas',
    'NumPy',
    'Matplotlib',
    'Seaborn',
    'Scikit-learn',
    'TensorFlow',
    'PyTorch',
    'Keras',
    'Jupyter',
    'Anaconda',
    'Tableau',
    'Power BI',
    'Excel',
    'Apache Spark',
    'Hadoop',
    'AWS',
    'Azure ML',
    'Google Colab',
    'Git',
    'Statistics',
    'Machine Learning',
  ],
  'devops-engineering': [
    'Docker',
    'Kubernetes',
    'AWS',
    'Azure',
    'Google Cloud',
    'Jenkins',
    'GitLab CI/CD',
    'GitHub Actions',
    'Terraform',
    'Ansible',
    'Chef',
    'Puppet',
    'Linux',
    'Bash',
    'Python',
    'Nginx',
    'Apache',
    'MySQL',
    'PostgreSQL',
    'Redis',
    'Elasticsearch',
    'Prometheus',
    'Grafana',
    'ELK Stack',
  ],
  'blockchain-development': [
    'Solidity',
    'JavaScript',
    'TypeScript',
    'Web3.js',
    'Ethers.js',
    'React',
    'Node.js',
    'Truffle',
    'Hardhat',
    'Remix',
    'MetaMask',
    'IPFS',
    'Bitcoin',
    'Ethereum',
    'Smart Contracts',
    'DeFi',
    'NFTs',
    'Rust',
    'Go',
    'Python',
  ],
};

export const trackRequirements = {
  'frontend-development': {
    title: 'Frontend Development',
    description:
      'Build modern, responsive web applications using cutting-edge technologies',
    duration: '6 months',
    level: 'Beginner to Advanced',
    prerequisites: 'Basic understanding of HTML, CSS, and JavaScript',
    outcomes: [
      'Master React.js and modern JavaScript',
      'Build responsive designs with CSS frameworks',
      'Work with APIs and state management',
      'Deploy applications to production',
    ],
  },
  'backend-development': {
    title: 'Backend Development',
    description: 'Create robust server-side applications and APIs',
    duration: '6 months',
    level: 'Beginner to Advanced',
    prerequisites: 'Programming fundamentals in any language',
    outcomes: [
      'Build RESTful APIs and microservices',
      'Work with databases and data modeling',
      'Implement authentication and security',
      'Deploy scalable backend systems',
    ],
  },
  'fullstack-development': {
    title: 'Full Stack Development',
    description:
      'Become a complete web developer with both frontend and backend skills',
    duration: '8 months',
    level: 'Intermediate to Advanced',
    prerequisites: 'Basic web development knowledge',
    outcomes: [
      'Build complete web applications',
      'Master both client and server technologies',
      'Implement full authentication systems',
      'Deploy full-stack applications',
    ],
  },
  'mobile-development': {
    title: 'Mobile Development',
    description: 'Create native and cross-platform mobile applications',
    duration: '6 months',
    level: 'Beginner to Advanced',
    prerequisites: 'Programming fundamentals',
    outcomes: [
      'Build iOS and Android applications',
      'Master React Native or Flutter',
      'Integrate with mobile device features',
      'Publish apps to app stores',
    ],
  },
  'product-management': {
    title: 'Product Management',
    description:
      'Learn to strategize, plan, and execute successful digital products',
    duration: '4 months',
    level: 'Beginner to Intermediate',
    prerequisites: 'No technical background required',
    outcomes: [
      'Develop product strategy and roadmaps',
      'Conduct user research and analysis',
      'Manage cross-functional teams',
      'Launch successful products',
    ],
  },
  'product-design': {
    title: 'Product Design (UI/UX)',
    description: 'Design beautiful and user-friendly digital experiences',
    duration: '5 months',
    level: 'Beginner to Advanced',
    prerequisites: 'Basic design sense and creativity',
    outcomes: [
      'Master design thinking and user research',
      'Create wireframes and high-fidelity designs',
      'Build interactive prototypes',
      'Conduct usability testing',
    ],
  },
  'data-science': {
    title: 'Data Science',
    description:
      'Extract insights from data using statistical analysis and machine learning',
    duration: '7 months',
    level: 'Intermediate to Advanced',
    prerequisites: 'Mathematics and statistics background',
    outcomes: [
      'Analyze and visualize complex datasets',
      'Build predictive models with ML',
      'Work with big data technologies',
      'Present data-driven insights',
    ],
  },
  'devops-engineering': {
    title: 'DevOps Engineering',
    description: 'Streamline software development and deployment processes',
    duration: '6 months',
    level: 'Intermediate to Advanced',
    prerequisites: 'Linux and programming knowledge',
    outcomes: [
      'Implement CI/CD pipelines',
      'Manage cloud infrastructure',
      'Automate deployment processes',
      'Monitor and scale applications',
    ],
  },
  'blockchain-development': {
    title: 'Blockchain Development',
    description: 'Build decentralized applications and smart contracts',
    duration: '6 months',
    level: 'Intermediate to Advanced',
    prerequisites: 'Programming experience (JavaScript/Python)',
    outcomes: [
      'Develop smart contracts with Solidity',
      'Build DeFi and Web3 applications',
      'Understand blockchain fundamentals',
      'Deploy to mainnet and testnets',
    ],
  },
};

export const getToolsForTrack = (trackId: string): string[] => {
  return trackTools[trackId as keyof typeof trackTools] || [];
};

export const getTrackInfo = (trackId: string) => {
  return trackRequirements[trackId as keyof typeof trackRequirements] || null;
};
