import { routeCreator } from "../utils";

export const urls = {
  health: {
    entry: () => routeCreator("health"),
    root: () => "/", // optional, for clarity
    detailed: () => "/detailed",
    liveness: () => "/liveness",
    readiness: () => "/readiness",
  },
  auth: {
    entry: () => routeCreator("auth"),
    login: () => "/login",
    resetPassword: () => "/reset-password",
    profile: () => "/profile",
  },
  applications: {
    entry: () => routeCreator("applications"),
    apply: () => "/apply",
    list: () => "/",
    review: (id: string) => `/${id}/review`,
    accept: (id: string) => `/${id}/accept`,
    reject: (id: string) => `/${id}/reject`,
    details: (id: string) => `/${id}`,
  },
  cohorts: {
    entry: () => routeCreator("cohorts"),
    list: () => "/",
    create: () => "/create",
    active: () => "/active",
    currentActive: () => "/current-active",
    details: (id: string) => `/${id}`,
    update: (id: string) => `/${id}`,
    delete: (id: string) => `/${id}`,
  },
  tracks: {
    entry: () => routeCreator("tracks"),
    list: () => "/",
    create: () => "/create",
    details: (id: string) => `/${id}`,
    update: (id: string) => `/${id}`,
    delete: (id: string) => `/${id}`,
  },
  users: {
    entry: () => routeCreator("users"),
    list: () => "/",
    create: () => "/create",
    details: (id: string) => `/${id}`,
    update: (id: string) => `/${id}`,
    delete: (id: string) => `/${id}`,
    assignTracks: (id: string) => `/${id}/assign-tracks`,
    toggleStatus: (id: string) => `/${id}/toggle-status`,
  },
  assessments: {
    entry: () => routeCreator("assessments"),
    list: () => "/",
    submit: () => "/submit",
    details: (id: string) => `/${id}`,
    review: (id: string) => `/${id}/review`,
  },
  interviews: {
    entry: () => routeCreator("interviews"),
    list: () => "/",
    slots: {
      create: () => "/slots",
      mySlots: () => "/slots/my-slots",
      available: () => "/slots/available",
    },
    schedule: () => "/schedule",
    details: (id: string) => `/${id}`,
    byApplication: (applicationId: string) => `/application/${applicationId}`,
    review: (id: string) => `/${id}/review`,
    cancel: (id: string) => `/${id}/cancel`,
  },
  emailTemplates: {
    entry: () => routeCreator("email-templates"),
    list: () => "/",
    create: () => "/",
    details: (id: string) => `/${id}`,
    update: (id: string) => `/${id}`,
    delete: (id: string) => `/${id}`,
    preview: (id: string) => `/${id}/preview`,
    test: (id: string) => `/${id}/test`,
    send: () => "/send",
    variables: () => "/variables",
    recipients: () => "/recipients/list",
    logs: () => "/logs/history",
  },
  directEmail: {
    entry: () => routeCreator("direct-email"),
    send: () => "/send",
    bulk: () => "/bulk",
    history: () => "/history",
  },
  streams: {
    entry: () => routeCreator("streams"),
    list: () => "/",
    create: () => "/",
    details: (id: string) => `/${id}`,
    update: (id: string) => `/${id}`,
    delete: (id: string) => `/${id}`,
    reactions: (id: string) => `/${id}/reactions`,
    comments: (id: string) => `/${id}/comments`,
  },
  tasks: {
    entry: () => routeCreator("tasks"),
    list: () => "/",
    create: () => "/",
    details: (id: string) => `/${id}`,
    update: (id: string) => `/${id}`,
    delete: (id: string) => `/${id}`,
    submit: (id: string) => `/${id}/submit`,
    submissions: (id: string) => `/${id}/submissions`,
    grade: (id: string, submissionId: string) =>
      `/${id}/submissions/${submissionId}/grade`,
  },
  materials: {
    entry: () => routeCreator("materials"),
    list: () => "/",
    create: () => "/",
    details: (id: string) => `/${id}`,
    update: (id: string) => `/${id}`,
    delete: (id: string) => `/${id}`,
  },
};
